---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: ansible
ansible_password: ansible
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# Common AVD group variables
fabric_name: CLAB_DC1

# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
# p2p_uplinks_mtu: 1500
p2p_uplinks_mtu: 1500

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: EBGP
overlay_routing_protocol: EBGP

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==

# Local users
local_users:
  # Define a new user, which is called "ansible"
  ansible:
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9r+4jpU707tl3Lzgu79Ch1rLI9Ft0Hi9FKQ1oM5zeh/uE5UC+VuWy3kHmACjHDtrLVPtbzVtO+yJnfoeGUJCINdFv2KSl51ShvUKxDK3f0YQ9X7OC7eLhlQPdnQ+So+CRFQfd7aVmc0l7e8z3gkNvnQxdKqhSmZZJNQ2RJYVgYtzZFK/UUv28SFS9ZCxDWdaCQCOj/iFV3z0mBupFUvuJx11IJEY3/JjUAQwWiMh8tvyOPueLj7H2lCGwMabfCqPZVMGqDM+dso2BTajBLVVykxLG/xIZPq6Nmn5M4SHNTc6kprAw4mh4y10CbwZwa+TvlNXv5V4GRVjOetjuuAswWOXKpGQSqQ0WUL50Hjwvv44fGlF5Pf7um3udIEZwY5Pp6IbK9rmuiqD1fV4HFesIRMkgysePsUkuT7HhN5AepplIjuBrkpnSmzpuTSOPXhFNaRZUeBbeWTIRgyY/3Nu1oX0pu6prZP72XXNzY2xmKWuHvIxT2K+ah760NctjWFs= ja@cyril
  cvpadmin:
    privilege: 15
    role: network-admin
    # Password set to "arista123". Same string as the device generates when configuring a username.
    sha512_password: $6$2bHwIrJcm32HV1Lw$GvWawZtW3ReBJmJarBAoiBA7XofdAbXuW5ob13LUX/0nBIdEPhhJdGkodo8qQyBngyMq9OgVTAmYULafLVlDB0
  ja:
    privilege: 15
    role: network-admin
    # Password set to "arista123". Same string as the device generates when configuring a username.
    sha512_password: $6$2bHwIrJcm32HV1Lw$GvWawZtW3ReBJmJarBAoiBA7XofdAbXuW5ob13LUX/0nBIdEPhhJdGkodo8qQyBngyMq9OgVTAmYULafLVlDB0
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9r+4jpU707tl3Lzgu79Ch1rLI9Ft0Hi9FKQ1oM5zeh/uE5UC+VuWy3kHmACjHDtrLVPtbzVtO+yJnfoeGUJCINdFv2KSl51ShvUKxDK3f0YQ9X7OC7eLhlQPdnQ+So+CRFQfd7aVmc0l7e8z3gkNvnQxdKqhSmZZJNQ2RJYVgYtzZFK/UUv28SFS9ZCxDWdaCQCOj/iFV3z0mBupFUvuJx11IJEY3/JjUAQwWiMh8tvyOPueLj7H2lCGwMabfCqPZVMGqDM+dso2BTajBLVVykxLG/xIZPq6Nmn5M4SHNTc6kprAw4mh4y10CbwZwa+TvlNXv5V4GRVjOetjuuAswWOXKpGQSqQ0WUL50Hjwvv44fGlF5Pf7um3udIEZwY5Pp6IbK9rmuiqD1fV4HFesIRMkgysePsUkuT7HhN5AepplIjuBrkpnSmzpuTSOPXhFNaRZUeBbeWTIRgyY/3Nu1oX0pu6prZP72XXNzY2xmKWuHvIxT2K+ah760NctjWFs= ja@cyril
  admin:
    privilege: 15
    role: network-admin
    no_password: true

# CloudVision - Telemetry Agent (TerminAttr) configuration | Optional
# You can either provide a list of IPs to target on-premise CloudVision cluster or
# use DNS name for your CloudVision as a Service instance. If you have both on-prem and
# CVaaS defined, only on-prem is going to be configured.

daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - 192.168.88.8:9910
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: "token"
    token_file: "/tmp/token"
  cvvrf: MGMT
  cvcompression: gzip
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

# EOS CLI rendered directly on the device
eos_cli: |
  interface  Management1
    no lldp transmit
    no lldp receive