---
# Default gateway used for the management interface
mgmt_gateway: 192.168.123.1

# Adjust default bfd values, to avoid high CPU.
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# Spine switch group
spine:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.1.0/27
    # ASN to be used by BGP
    bgp_as: 65100
    # BGP configuration for fine tunning
    bgp_defaults:
      # The two folling commands must not be enabled when using vEOS-lab
      # - update wait-for-convergence
      # - update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart

  # Definition of nodes contained in this group.
  # Specific configuration of device must take place under the node definition. Each node inherites all values defined under 'defaults'
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    dc1-spine1:
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 1
      # Management IP to be assigned to the management interface
      mgmt_ip: 192.168.123.11/24

    dc1-spine2:
      id: 2
      mgmt_ip: 192.168.123.12/24

# L3 Leaf switch group
l3leaf:
  defaults:
    platform: cEOS-lab
    loopback_ipv4_pool: 10.255.1.32/27
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.11.0/27
    # Interfaces connecting this device towards the upper level of the hierarchy (Spines in this case)
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1']
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['dc1-spine1', 'dc1-spine2']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # MLAG Peer link physical interface definition
    mlag_interfaces: ['Ethernet53/1', 'Ethernet54/1']
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    bgp_defaults:
      # The folling command must not be enabled when using vEOS-lab
      # - update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  # If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    DC3_L3_LEAF1:
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65101
      nodes:
        # Definition of hostnames under the node_group
        dc1-leaf1a:
          id: 1
          mgmt_ip: 192.168.123.21/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet1/1
            - Ethernet1/1
        dc1-leaf1b:
          id: 2
          mgmt_ip: 192.168.123.22/24
          uplink_switch_interfaces:
            - Ethernet2/1
            - Ethernet2/1

    DC3_L3_LEAF2:
      bgp_as: 65102
      nodes:
        dc1-leaf2a:
          id: 3
          mgmt_ip: 192.168.123.23/24
          uplink_switch_interfaces:
            - Ethernet3/1
            - Ethernet3/1
        dc1-leaf2b:
          id: 4
          mgmt_ip: 192.168.123.24/24
          uplink_switch_interfaces:
            - Ethernet4/1
            - Ethernet4/1

