---
- hosts: CLAB_DC1_FABRIC
  gather_facts: false
  tasks: 
  - name: Restore config and save
    eos_command:
      commands:
        - config replace flash:acb22-cvp-onboarded
        - copy run start

