---
- hosts: CLAB_DC1_FABRIC
  gather_facts: no
  tasks: 
  - name: TerminAttr config tokens
    eos_command:
      commands:
        - "enable"
        - "config"
        - "daemon TerminAttr"
        - "exec /usr/bin/TerminAttr -cvaddr=192.168.88.8:9910 -cvauth=token,/tmp/token -cvvrf=MGMT -cvgnmi -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs"
        - "shut"
        - "no shut"
